### ISSUE TITLE
New Issues

### ISSUE THREAD

**Issue by JimmySoundsGood** [cswclui/SimPsyber#2] opened 2022-02-19 09:15 UTC
When i failed the game and attempted to play it again, the game was not working at all even through you had assigned the task with certain worker, the timing system is stuck. I have to close the browser and revisit the page again.

**Comment by Flyingblu** [comment] 2022-02-20 14:28
Can confirm, I have found the same issue.

**Comment by cswclui** [comment] 2022-03-06 07:25
Thanks for reporting. This defect should have been fixed now.
Seems this issue is the duplicate of the bug report by hugo22565 #1

**Closed** 2022-03-06 07:29 UTC
